package com.myronmarston.music.settings;

/**
 * Used as a hash key to access a particular VoiceSection.
 * 
 * @author Myron
 */
public class VoiceSectionHashMapKey {
    private Voice voice;
    private Section section;
    
    /**
     * Constructor.
     * 
     * @param voice the Voice for this key
     * @param section the Section for this key
     */
    public VoiceSectionHashMapKey(Voice voice, Section section) {
        this.voice = voice;
        this.section = section;
    }    
    
    /**
     * Gets the Section for this key.
     * 
     * @return the Section for this key
     */
    public Section getSection() {
        return section;
    }

    /**
     * Gets the Voice for this key.
     * 
     * @return the Voice for this key
     */
    public Voice getVoice() {
        return voice;
    }

    // equals() and hashCode() were generated by Netbeans IDE.
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final VoiceSectionHashMapKey other = (VoiceSectionHashMapKey) obj;
        if (this.voice != other.voice && (this.voice == null || !this.voice.equals(other.voice))) {
            return false;
        }
        if (this.section != other.section && (this.section == null || !this.section.equals(other.section))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + (this.voice != null ? this.voice.hashCode() : 0);
        hash = 41 * hash + (this.section != null ? this.section.hashCode() : 0);
        return hash;
    }        
}
