package com.myronmarston.music;

/**
 * Represents a note, relative to a particular scale.
 * The note doesn't know or care what scale is being used, but to get a concrete
 * MidiNote, the scale must be used to convert it.
 * @author Myron
 */
public class Note {   
    private int scaleStep; //0 = tonic, 7 = octave, 9 = third an octave above, etc.
    private int octave; //which octave the note should be in.  0 begins the first octave in Midi that contains the tonic.
    private int chromaticAdjustment; //-2...2.  If this is an accidental, the number of half steps to adjust it from the diatonic scale note.
    private double duration; //how long the note should last, in quarter notes.
    private int volume = MidiNote.DEFAULT_VELOCITY; //how loud the note should be on a scale from 0 to 127.    
    
    public Note() {}
            
    public Note(int scaleStep, int octave, int chromaticAdjustment, double duration, int volume) {
        this.scaleStep = scaleStep;
        this.octave = octave;
        this.chromaticAdjustment = chromaticAdjustment;
        this.setDuration(duration);
        this.volume = volume;
    }
    
    // Copy constructor
    public Note(Note inputNote) {
        this(inputNote.getScaleStep(), inputNote.getOctave(), inputNote.getChromaticAdjustment(), inputNote.getDuration(), inputNote.getVolume());        
    }
    
    static public Note createRest(double duration) {
        Note rest = new Note();
                
        rest.setDuration(duration); // use the setter so we get an exception if the duration is 0
        rest.setVolume(0);
        
        assert rest.isRest() : rest;
        return rest;
    }

    public int getScaleStep() {
        return scaleStep;
    }

    public void setScaleStep(int scaleStep) {
        throwUnsupportedOperationExceptionIfRest("scaleStep", scaleStep);
        this.scaleStep = scaleStep;        
    }

    public int getOctave() {
        return octave;
    }

    public void setOctave(int octave) {
        throwUnsupportedOperationExceptionIfRest("octave", octave);
        this.octave = octave;        
    }

    public int getChromaticAdjustment() {
        return chromaticAdjustment;
    }

    public void setChromaticAdjustment(int chromaticAdjustment) { 
        throwUnsupportedOperationExceptionIfRest("chromaticAdjustment", chromaticAdjustment);
        this.chromaticAdjustment = chromaticAdjustment;
    }

    public double getDuration() {
        return duration;
    }

    public void setDuration(double duration) {
        if (duration <= 0) throw new IllegalArgumentException("The duration must be greater than zero.");
        this.duration = duration;
    }

    public int getVolume() {
        return volume;
    }

    public void setVolume(int volume) {        
        this.volume = volume;  
        setValuesForRest();
    }
    
    public boolean isRest() {
        return (0 == this.getVolume());
    }    
    
    protected void throwUnsupportedOperationExceptionIfRest(String changingField, int value) {
        if (this.isRest() && value != 0) { // each of the fields can be zero...
            throw new UnsupportedOperationException(String.format("The Note is a rest.  The %s field cannot be changed on a rest.", changingField));
        }
    }
    
    protected void setValuesForRest() {
        if (this.isRest()) {
            this.setScaleStep(0);
            this.setOctave(0);
            this.setChromaticAdjustment(0);
        }        
    }
    
    // equals and hashCode have been auto-generated by NetBeans.
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Note other = (Note) obj;
        if (this.scaleStep != other.scaleStep) {
            return false;
        }
        if (this.octave != other.octave) {
            return false;
        }
        if (this.chromaticAdjustment != other.chromaticAdjustment) {
            return false;
        }
        if (this.duration != other.duration) {
            return false;
        }
        if (this.volume != other.volume) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + this.scaleStep;
        hash = 89 * hash + this.octave;
        hash = 89 * hash + this.chromaticAdjustment;
        hash = 89 * hash + (int) (Double.doubleToLongBits(this.duration) ^ (Double.doubleToLongBits(this.duration) >>> 32));
        hash = 89 * hash + this.volume;
        return hash;
    }    
}
